name: mathematics_ai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  stylish_bottom_bar: ^1.1.0
  animated_bottom_navigation_bar: ^1.3.3
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Innova
      fonts:
        - asset: assets/fonts/Innova-Heavy.otf
        - asset: assets/fonts/Innova-Light.otf
        - asset: assets/fonts/Innova-Medium.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
